# Build.
FROM golang:1.21 AS build-stage
WORKDIR /
COPY go.mod go.sum ./
RUN go mod download
COPY . /
RUN CGO_ENABLED=0 GOOS=linux go build -o /entrypoint

# Deploy.
FROM gcr.io/distroless/static-debian11 AS release-stage
WORKDIR /
COPY --from=build-stage /entrypoint /entrypoint
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/entrypoint"]